[2025-01-31T01:24:20.399+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T01:24:20.405+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: youtube_comments_etl_pipeline.load_youtube_data manual__2025-01-31T01:24:14.461625+00:00 [queued]>
[2025-01-31T01:24:20.408+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: youtube_comments_etl_pipeline.load_youtube_data manual__2025-01-31T01:24:14.461625+00:00 [queued]>
[2025-01-31T01:24:20.408+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T01:24:20.412+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): load_youtube_data> on 2025-01-31 01:24:14.461625+00:00
[2025-01-31T01:24:20.415+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=716) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T01:24:20.416+0000] {standard_task_runner.py:72} INFO - Started process 717 to run task
[2025-01-31T01:24:20.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'youtube_comments_etl_pipeline', 'load_youtube_data', 'manual__2025-01-31T01:24:14.461625+00:00', '--job-id', '446', '--raw', '--subdir', 'DAGS_FOLDER/youtube_comments_DAG.py', '--cfg-path', '/tmp/tmp5xx_l7qk']
[2025-01-31T01:24:20.417+0000] {standard_task_runner.py:105} INFO - Job 446: Subtask load_youtube_data
[2025-01-31T01:24:20.436+0000] {task_command.py:467} INFO - Running <TaskInstance: youtube_comments_etl_pipeline.load_youtube_data manual__2025-01-31T01:24:14.461625+00:00 [running]> on host 8155aa75e0ca
[2025-01-31T01:24:20.622+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='youtube_comments_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_youtube_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T01:24:14.461625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-31T01:24:14.461625+00:00'
[2025-01-31T01:24:20.622+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-31T01:24:20.622+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-31T01:24:20.622+0000] {logging_mixin.py:190} INFO - Current task name:load_youtube_data state:running start_date:2025-01-31 01:24:20.405608+00:00
[2025-01-31T01:24:20.623+0000] {logging_mixin.py:190} INFO - Dag name:youtube_comments_etl_pipeline and current dag run status:running
[2025-01-31T01:24:20.623+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T01:24:20.626+0000] {base.py:84} INFO - Retrieving connection 'youtube_connection'
[2025-01-31T01:24:20.631+0000] {logging_mixin.py:190} INFO - records: [('@analyticswithadam', '2024-02-06T21:00:47Z', '2024-02-06T21:00:47Z', 4, 'Updated Video a href')]
[2025-01-31T01:24:20.631+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/youtube_comments_DAG.py", line 125, in load_youtube_data
    cursor.execute(insert_query, record)
psycopg2.ProgrammingError: can't adapt type 'numpy.int64'
[2025-01-31T01:24:20.635+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-31T01:24:20.636+0000] {logging_mixin.py:190} INFO - Task start:2025-01-31 01:24:20.405608+00:00 end:2025-01-31 01:24:20.635724+00:00 duration:0.230116
[2025-01-31T01:24:20.636+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): load_youtube_data> dag:<DAG: youtube_comments_etl_pipeline> dagrun:<DagRun youtube_comments_etl_pipeline @ 2025-01-31 01:24:14.461625+00:00: manual__2025-01-31T01:24:14.461625+00:00, state:running, queued_at: 2025-01-31 01:24:14.479672+00:00. externally triggered: True>
[2025-01-31T01:24:20.636+0000] {logging_mixin.py:190} INFO - Failure caused by can't adapt type 'numpy.int64'
[2025-01-31T01:24:20.636+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=youtube_comments_etl_pipeline, task_id=load_youtube_data, run_id=manual__2025-01-31T01:24:14.461625+00:00, execution_date=20250131T012414, start_date=20250131T012420, end_date=20250131T012420
[2025-01-31T01:24:20.640+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T01:24:20.640+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 446 for task load_youtube_data (can't adapt type 'numpy.int64'; 717)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/youtube_comments_DAG.py", line 125, in load_youtube_data
    cursor.execute(insert_query, record)
psycopg2.ProgrammingError: can't adapt type 'numpy.int64'
[2025-01-31T01:24:20.690+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-31T01:24:20.710+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T01:24:20.713+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
